version: "3.9"

services:
  db:
    image: mysql:8
    container_name: financetracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financetracker
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net

  backend:
    build: ./backend
    container_name: financetracker-backend
    ports:
      - "9090:8080"
    depends_on:
      - db
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: financetracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mysql_data: