spring.application.name=FinanceTracker

#logging
logging.level.org.springframework=INFO
logging.file.name=logs/application.log

# Database connection
spring.datasource.url= jdbc:mysql://db:3306/financetracker
spring.datasource.username= appuser
spring.datasource.password= apppass
spring.jpa.hibernate.ddl-auto= update

spring.security.oauth2.resourceserver.jwt.secret-key=myfinances-super-secure-key-2025-!@#
